#!/bin/bash

run-test ()
{
    local theUnit=${1};shift

    theCommand="clang++ \
        -std=c++14 \
        -stdlib=libc++ \
        ${theUnit}.cpp \
        -o ${theUnit}"

    ${theCommand}

    rm ${theUnit}
}

run-test units-test
run-test quantity-test
